name = "booking-poc"
main = "src/worker.js"
compatibility_date = "2024-01-01"

# Set these with: wrangler secret put <NAME>
# CYBS_MERCHANT_ID
# CYBS_KEY_ID
# CYBS_SHARED_SECRET
# SHEET_WEBAPP_URL   (the Google Apps Script Web App URL, can be a plain var for POC)
# CYBS_WEBHOOK_SECRET (/kms/egress/v2/keys-sym)

[vars]
CYBS_ENV = "production" # apitest.cybersource.com for sandbox, api.cybersource.com for production
SHEET_WEBAPP_URL = "https://script.google.com/macros/s/AKfycbwS4nlG0mzm6m55PJyZuO3hH08uny-FP9s1ye4sOOH4w7Vq0psZzekGsQRFWIk6AWhZWg/exec"
# CHECKOUT_ORIGIN = "https://book.yourresort.com"

[triggers]
crons = ["*/5 * * * *"] # reconciliation every 5 minutes
