name = "booking-poc"
main = "src/worker.js"
compatibility_date = "2024-01-01"

# Set these with: wrangler secret put <NAME>
# CYBS_MERCHANT_ID
# CYBS_KEY_ID
# CYBS_SHARED_SECRET
# SHEET_WEBAPP_URL   (the Google Apps Script Web App URL, can be a plain var for POC)
# CYBS_WEBHOOK_SECRET (/kms/egress/v2/keys-sym)

[vars]
CYBS_ENV = "production" # apitest.cybersource.com for sandbox, api.cybersource.com for production
CYBS_CURRENCY = "NPR"

SHEET_WEBAPP_URL = "https://script.google.com/macros/s/AKfycbwFqiwuF_xV0YreAehDBc1sDSNInrnTQgidYCvkwHinxoWEN7krFxkhCvtnY8g3qh5faw/exec"
CHECKOUT_ORIGIN = "https://book.krishna-sharma.com.np"
DEBUG_ENABLED = "true"

[triggers]
crons = ["*/30 * * * *"]  # reconciliation every 30 minutes

[[routes]]
pattern = "book.krishna-sharma.com.np"
custom_domain = true
 